name: faers-env
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - numpy
  - pytorch
  - scikit-learn
  - matplotlib
  - pandas
    - python=3.10
  - jupyter
  - requests
  - duckdb
  - tqdm
      - openfda
      - rxnorm

