[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "faers-212"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
loguru = ">=0.7.2,<0.8"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.5,<3"
tqdm = ">=4.67.1,<5"
ipykernel = ">=6.29.5,<7"
statsmodels = ">=0.14.4,<0.15"
scipy = ">=1.15.2,<2"
requests = ">=2.32.3,<3"
bs4 = ">=4.13.4,<5"
lxml = ">=5.4.0,<6"
